# Copyright 2019 Contributors to Hyperledger Sawtooth
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "3"

services:
  shell:
    build:
      context: .
      dockerfile: ./docker/tests.Dockerfile
    container_name: rbac-shell
    image: rbac-shell:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    depends_on:
      - rest-api
    command: tail -f /dev/null
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - PYTHONPATH=/project/hyperledger-rbac/
      - SERVER_HOST=${SERVER_HOST:-rbac-server}
      - SERVER_PORT=${SERVER_PORT:-8000}
      - VALIDATOR_HOST=${VALIDATOR_HOST:-validator}
      - VALIDATOR_PORT=${VALIDATOR_PORT:-4004}
      - VALIDATOR_TIMEOUT=${VALIDATOR_TIMEOUT:-500}
      - DB_HOST=${DB_HOST:-rethink}
      - DB_PORT=${DB_PORT:-28015}
      - DB_NAME=${DB_NAME:-rbac}
      - SECRET_KEY=${SECRET_KEY}
      - AES_KEY=${AES_KEY}

  rbac-provider-azure:
    build:
      context: .
      dockerfile: ./docker/rbac.providers.azure.Dockerfile
    container_name: rbac-providers-azure
    image: rbac-provider-azure:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    environment:
      - AUTH_TYPE=${AUTH_TYPE}
      - AAD_EH_SAS_POLICY=${AAD_EH_SAS_POLICY}
      - AAD_EH_SAS_KEY=${AAD_EH_SAS_KEY}
      - AAD_EH_CONSUMER_GROUP=${AAD_EH_CONSUMER_GROUP}
      - AAD_EH_NAMESPACE=${AAD_EH_NAMESPACE}
      - AAD_EH_NAME=${AAD_EH_NAME}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLIENT_ASSERTION=${CLIENT_ASSERTION}
      - ENABLE_AZURE_SYNC=${ENABLE_AZURE_SYNC:-False}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - TENANT_ID=${TENANT_ID}
    depends_on:
      - ledger-sync
    command: ./bin/rbac-providers-azure

  rbac-provider-ldap:
    build:
      context: .
      dockerfile: ./docker/rbac.providers.ldap.Dockerfile
    container_name: rbac-providers-ldap
    image: rbac-provider-ldap:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    environment:
      - DELTA_SYNC_INTERVAL_SECONDS=${DELTA_SYNC_INTERVAL_SECONDS:-3600}
      - ENABLE_LDAP_SYNC=${ENABLE_LDAP_SYNC:-False}
      - LDAP_DC=${LDAP_DC}
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_USER=${LDAP_USER}
      - LDAP_PASS=${LDAP_PASS}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - USER_BASE_DN=${USER_BASE_DN}
      - GROUP_BASE_DN=${GROUP_BASE_DN}
    depends_on:
      - ledger-sync
    command: ./bin/rbac-providers-ldap

  rbac-bootstrap-worker:
    build:
      context: .
      dockerfile: ./docker/bootstrap.Dockerfile
    container_name: rbac-bootstrap-worker
    image: rbac-bootstrap-worker:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - NEXT_ADMIN_NAME=${NEXT_ADMIN_NAME}
      - NEXT_ADMIN_USER=${NEXT_ADMIN_USER}
      - NEXT_ADMIN_PASS=${NEXT_ADMIN_PASS}
      - NEXT_ADMIN_EMAIL=${NEXT_ADMIN_EMAIL}
      - DB_HOST=${DB_HOST:-rethink}
      - DB_PORT=${DB_PORT:-28015}
      - DB_NAME=${DB_NAME:-rbac}
    depends_on:
      - rbac-server
    command: ./bin/bootstrap

  rbac-server:
    build:
      context: .
      dockerfile: ./docker/rbac.server.Dockerfile
    container_name: rbac-server
    image: rbac-server:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    depends_on:
      - ledger-sync
      - rethink
      - validator
    environment:
      - ADAPI_HOST=${ADAPI_HOST}
      - ADAPI_PORT=${ADAPI_PORT}
      - ADAPI_USERNAME=${ADAPI_USERNAME}
      - ADAPI_PASSWORD=${ADAPI_PASSWORD}
      - AES_KEY=${AES_KEY}
      - CLIENT_HOST=${CLIENT_HOST}
      - CLIENT_PORT=${CLIENT_PORT}
      - DB_HOST=${DB_HOST:-rethink}
      - DB_PORT=${DB_PORT:-28015}
      - DB_NAME=${DB_NAME:-rbac}
      - ENABLE_AZURE_SYNC=${ENABLE_AZURE_SYNC:-0}
      - ENABLE_LDAP_SYNC=${ENABLE_LDAP_SYNC:-0}
      - ENABLE_NEXT_BASE_USE=${ENABLE_NEXT_BASE_USE:-1}
      - HOST=${HOST:-localhost}
      - LDAP_DC=${LDAP_DC}
      - LDAP_SERVER=${LDAP_SERVER}
      - GROUP_BASE_DN=${GROUP_BASE_DN}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_PORT=${SERVER_PORT:-8000}
      - SECRET_KEY=${SECRET_KEY}
      - TENANT_ID=${TENANT_ID}
      - NEXT_ADMIN_NAME=${NEXT_ADMIN_NAME}
      - NEXT_ADMIN_USER=${NEXT_ADMIN_USER}
      - NEXT_ADMIN_PASS=${NEXT_ADMIN_PASS}
      - NEXT_ADMIN_EMAIL=${NEXT_ADMIN_EMAIL}
    command: ./bin/rbac-server --db-host rethink --validator-host validator

  rethink-bootstrap-worker:
    build:
      context: .
      dockerfile: ./docker/rethink.bootstrap.Dockerfile
    container_name: rbac-rethink-bootstrap-worker
    image: rethink-bootstrap-worker:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    depends_on:
      - rethink
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - DB_HOST=${DB_HOST:-rethink}
      - DB_PORT=${DB_PORT:-28015}
      - DB_NAME=${DB_NAME:-rbac}
    command: ./bin/setup_db

  rethink:
    container_name: rbac-rethink
    image: rethinkdb:2.3
    expose:
      - "28015"

  rbac-tp:
    build:
      context: .
      dockerfile: ./docker/rbac.processor.Dockerfile
    container_name: rbac-tp
    image: rbac-tp:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    environment:
      - AES_KEY=${AES_KEY}
      - HOST=${HOST:-localhost}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - SECRET_KEY=${SECRET_KEY}
    command: ./bin/rbac-tp tcp://validator:4004

  ledger-sync:
    build:
      context: .
      dockerfile: ./docker/rbac.ledger_sync.Dockerfile
    container_name: rbac-ledger-sync
    image: rbac-ledger-sync:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    depends_on:
      - rethink-bootstrap-worker
      - validator
    environment:
      - AES_KEY=${AES_KEY}
      - ENABLE_AZURE_SYNC=${ENABLE_AZURE_SYNC:-0}
      - ENABLE_LDAP_SYNC=${ENABLE_LDAP_SYNC:-0}
      - ENABLE_NEXT_BASE_USE=${ENABLE_NEXT_BASE_USE:-1}
      - GROUP_BASE_DN=${GROUP_BASE_DN}
      - HOST=${HOST:-localhost}
      - LDAP_DC=${LDAP_DC}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - NEXT_ADMIN_USER=${NEXT_ADMIN_USER}
      - SECRET_KEY=${SECRET_KEY}
      - TENANT_ID=${TENANT_ID}
    healthcheck:
      test: ./bin/wait_for_ledger_sync
      interval: 30s
      timeout: 10s
      retries: 5
    command: |
      bash -c "
        ./bin/rbac-ledger-sync --db-host rethink --validator tcp://validator:4004
      \"\""

  client:
    build:
      context: .
      dockerfile: ./docker/client.Dockerfile
    container_name: rbac-client
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_PATH=${NODE_PATH-src/}
      - REACT_APP_DEFAULT_LANDING=${REACT_APP_DEFAULT_LANDING}
      - REACT_APP_HTTP_PROTOCOL=${REACT_APP_HTTP_PROTOCOL}
      - REACT_APP_SERVER_HOST=${REACT_APP_SERVER_HOST}
      - REACT_APP_SERVER_PORT=${REACT_APP_SERVER_PORT}
      - REACT_APP_WS_PROTOCOL=${REACT_APP_WS_PROTOCOL}
      - REACT_APP_VERSION_NUMBER=${VERSION_NUMBER}
      - REACT_APP_ENABLE_NEXT_BASE_USE=${ENABLE_NEXT_BASE_USE}
      - REACT_APP_ENABLE_LDAP_SYNC=${ENABLE_LDAP_SYNC}
    image: rbac-client:${ISOLATION_ID-latest}
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - rbac-server

  chatbot:
    build:
      context: .
      dockerfile: ./docker/chatbot.Dockerfile
    container_name: rbac-chatbot
    image: rbac-chatbot:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"

  rest-api:
    container_name: sawtooth-rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    ports:
      - "8008:8008"
    depends_on:
      - validator
    command: sawtooth-rest-api --connect tcp://validator:4004 --bind rest-api:8008

  settings-tp:
    container_name: rbac-settings-tp
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp --connect tcp://validator:4004

  validator:
    container_name: rbac-validator-tp
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
    image: hyperledger/sawtooth-validator:1.0
    entrypoint: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key &&
          sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
          --scheduler parallel
      \"\""
