# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "2"

services:
  rbac-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile-dev
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: rbac-server-dev:${ISOLATION_ID}
    volumes:
      - ".:/project/tmobile-rbac"
    ports:
      - "8000:8000"
    depends_on:
      - ledger-sync
      - rethink
      - validator
    command: ./bin/rbac-server --host 0.0.0.0 --db-host rethink --validator-host validator

  rethink:
    image: rethinkdb:2.3
    ports:
      - "9090:8080"

  rbac-tp:
    build:
      context: .
      dockerfile: ./processor/Dockerfile-dev
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: rbac-tp-dev:${ISOLATION_ID}
    volumes:
      - ".:/project/tmobile-rbac"
    command: ./bin/rbac-tp -vv tcp://validator:4004

  ledger-sync:
    build:
      context: .
      dockerfile: ./ledger_sync/Dockerfile-dev
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: rbac-ledger-sync-dev:${ISOLATION_ID}
    volumes:
      - ".:/project/tmobile-rbac"
    depends_on:
      - rethink
      - validator
    command: |
      bash -c "
        ./bin/setup_db --host rethink &&
        ./bin/rbac-ledger-sync -vv --db-host rethink --validator tcp://validator:4004
      "

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api
    ports:
      - "8008:8008"
    depends_on:
      - validator
    command: sawtooth-rest-api --connect tcp://validator:4004 --bind rest-api:8008 -vv

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.0
    command: |
      bash -c "
        sawadm keygen --force &&
        sawtooth keygen my_key --force &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch &&
        sawtooth-validator -v \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://*:4004 \
          --bind network:tcp://*:8800 \
          --scheduler parallel
      "
