# Copyright 2018 Contributors to Hyperledger Sawtooth
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "3"

services:
  shell:
    build:
      context: .
      dockerfile: ./shell/Dockerfile
    image: hyperledger/sawtooth-shell:1.0
    container_name: rbac-shell
    depends_on:
      - rest-api
    volumes:
      - ".:/project/tmobile-rbac"
    environment:
      - PYTHONPATH=/project/tmobile-rbac/
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_PORT=${SERVER_PORT:-8000}
      - VALIDATOR_HOST=${VALIDATOR_HOST:-validator}
      - VALIDATOR_PORT=${VALIDATOR_PORT:-4004}
      - VALIDATOR_TIMEOUT=${VALIDATOR_TIMEOUT:-500}
      - DB_HOST=${DB_HOST:-rethink}
      - DB_PORT=${DB_PORT:-28015}
      - DB_NAME=${DB_NAME:-rbac}
      - SECRET_KEY=${SECRET_KEY}
      - AES_KEY=${AES_KEY}

  rbac-server:
    build:
      context: .
      dockerfile: ./rbac/server/Dockerfile
    container_name: rbac-server
    image: rbac-server-production:${ISOLATION_ID-latest}
    ports:
      - "8000:8000"
    depends_on:
      - ledger-sync
      - rethink
      - validator
    environment:
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_PORT=${SERVER_PORT:-8000}
    command: ./bin/rbac-server --db-host rethink --validator-host validator

  rethink:
    container_name: rbac-rethink
    image: rethinkdb:2.3
    ports:
      - "9090:8080"

  rbac-tp:
    build:
      context: .
      dockerfile: ./rbac/processor/Dockerfile
    container_name: rbac-tp
    image: rbac-tp-production:${ISOLATION_ID-latest}
    environment:
      - HOST=${HOST:-localhost}
    command: ./bin/rbac-tp -vv tcp://validator:4004

  ledger-sync:
    build:
      context: .
      dockerfile: ./rbac/ledger_sync/Dockerfile
    container_name: rbac-ledger-sync
    image: rbac-ledger-sync-production:${ISOLATION_ID-latest}
    depends_on:
      - rethink
      - validator
    environment:
      - HOST=${HOST:-localhost}
    command: |
      bash -c "
        ./bin/setup_db --host rethink &&
        ./bin/rbac-ledger-sync -vv --db-host rethink --validator tcp://validator:4004
      \"\""

  rbac-ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    container_name: rbac-ui
    image: rbac-ui-production:${ISOLATION_ID-latest}
    ports:
      - "4200:4200"
    depends_on:
      - rbac-server
    environment:
      - HOST=${HOST:-localhost}

  rest-api:
    container_name: sawtooth-rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    ports:
      - "8008:8008"
    depends_on:
      - validator
    command: sawtooth-rest-api --connect tcp://validator:4004 --bind rest-api:8008 -vv

  settings-tp:
    container_name: rbac-settings-tp
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -v --connect tcp://validator:4004

  validator:
    container_name: rbac-validator-tp
    image: hyperledger/sawtooth-validator:1.0
    entrypoint: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key &&
          sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
          --scheduler parallel
      \"\""

