# Copyright 2019 Contributors to Hyperledger Sawtooth
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------------

%YAML 1.1
---
intents:
  - access
  - affirm
  - awe
  - bye
  - cancel
  - deny
  - expired
  - feeling
  - greet
  - help
  - insult
  - laugh
  - member
  - name
  - no_owner
  - offer
  - owner
  - pending
  - reason
  - recommend
  - request_access
  - thank
  - update
  - whoami

config:
  store_entities_as_slots: true

entities:
  - approver_name
  - batch_status
  - member_status
  - owner_status
  - reason
  - resource_id
  - resource_name
  - resource_type
  - token

forms: []

slots:
  approver_name:
    type: unfeaturized
  batch_status:
    type: categorical
    values:
      - 1 # COMMITTED
      - 2 # INVALID
      - 3 # PENDING
      - 4 # UNKNOWN
  member_status:
    type: categorical
    values:
      - PENDING
      - MEMBER
      - NOT_MEMBER
  owner_status:
    type: categorical
    values:
      - OWNER
  reason:
    type: unfeaturized
  resource_id:
    type: unfeaturized
  resource_name:
    type: unfeaturized
  resource_type:
    type: categorical
    values:
    - PACK
    - ROLE
  token:
    type: unfeaturized

actions:
  - action_request_access
  - utter_access_member
  - utter_access_pending
  - utter_ask_request_access
  - utter_awe
  - utter_bye
  - utter_current_draft_pack
  - utter_current_draft_role
  - utter_default
  - utter_exclame
  - utter_expired
  - utter_fanfare_sent
  - utter_feeling
  - utter_generic
  - utter_greet
  - utter_help
  - utter_insult
  - utter_laugh
  - utter_member
  - utter_name
  - utter_no_owner
  - utter_noop
  - utter_offer
  - utter_owner
  - utter_owner_not_member
  - utter_passive
  - utter_pending_pack
  - utter_pending_role
  - utter_recommendation
  - utter_recommended_draft_pack
  - utter_recommended_draft_role
  - utter_send_failure_invalid
  - utter_send_failure_pending
  - utter_send_failure_unknown
  - utter_standby
  - utter_thank
  - utter_whoami

templates:
  utter_noop:
    - text: /noop

  utter_offer:
    - text: >-
        Hi! Would you like me to request access to
        <strong>{resource_name}</strong> for you?
      buttons:
      - title: Yes, please
        payload: Yes, please.
      - title: No, thanks
        payload: No, thanks.

  utter_expired:
    - text: >-
        It looks like your membership to <strong>{resource_name}</strong>
        has expired. Don't worry. This is normal security stuff. Do you want
        me to request access for you again?
      buttons:
      - title: Yes, please
        payload: Yes, please.
      - title: No, thanks
        payload: No, thanks.

  utter_default:
    - text: Sorry, I didn't get that. Can you clarify?
    - text: I don't understand what you mean.

  utter_member:
    - text: You are a member of this resource.
    - text: Are you a member of this resource? Indeed you are.

  utter_owner:
    - text: You are an owner of this resource.
    - text: You own this! In other words, this belongs to you.
    - text: Congratulations, you are an owner of this resource.

  utter_owner_not_member:
    - text: >-
        You own this resource. However, you are not yet a member.
        Would you also like to become a member of your resource?
      buttons:
      - title: Yes, please
        payload: Yes, please.
      - title: No, thanks
        payload: No, thanks.

  utter_access_member:
    - text: You already have access to this resource, silly.

  utter_access_pending:
    - text: You've already requested access to this resource.

  utter_standby:
    - text: Feel free to ping me anytime.
    - text: I'll be here for you.

  utter_passive:
    - text: Fine.
    - text: Have it your way.

  utter_whoami:
    - text: >-
        I am Nex, a robot designed specifically to help
        you because you are very special and deserve it.

  utter_recommendation:
    - text: >-
        Hi! Based on your role, I bet having access
        to <strong>{resource_name}</strong> would make it easier for you
        to function.

  utter_ask_request_access:
    - text: Do you want me to request access for you?
      buttons:
      - title: Yes, please
        payload: Yes, please.
      - title: No, thanks
        payload: No, thanks.

  utter_name:
    - text: It's a pleasure getting to know you.
    - text: That's great.
    - text: Cool stuff.
    - text: Uh huh.

  utter_greet:
    - text: Bonjour! How can I help you?
    - text: Hola!
    - text: Sup?
    - text: Howdy partner.
    - text: Oh hi there.
    - text: What's up?
    - text: How may I serve you?

  utter_help:
    - text: >-
        I'm here to help you get access to resources
        you need.

  utter_insult:
    - text: >-
        I'm trying my best to be helpful. Please let
        me know more clearly how I can help you.
    - text: >-
        All robots make mistakes at some point. Please tell
        me what it is you'd like me to do.

  utter_recommended_draft_role:
    - text: >-
        So you'd like to request access to <strong>{resource_name}</strong>?
        Great. All you need to do is draft a note for <strong>{approver_name}</strong>
        and I'll take care of the rest.
      buttons:
        - title: Send request
          payload: '/request_access{"reason": "-", "resource_id": "-", "resource_type": "-"}'
        - title: Nevermind
          payload: Nevermind.

  utter_recommended_draft_pack:
    - text: >-
        So you want access to <strong>{resource_name}</strong>?
        Awesome. All you need to do is draft a note. I'll send the note to each approver
        and then move this pack to your pending requests!
      buttons:
        - title: Send request
          payload: '/request_access{"reason": "-", "resource_id": "-", "resource_type": "-"}'
        - title: Actually...
          payload: Nevermind.

  utter_current_draft_role:
    - text: >-
        Okay. So you need access to <strong>{resource_name}</strong>?
        Go ahead and draft a note for <strong>{approver_name}</strong>
        and I'll get on it.
      buttons:
        - title: Send request
          payload: '/request_access{"reason": "-", "resource_id": "-", "resource_type": "-"}'
        - title: Actually...
          payload: Nevermind.

  utter_current_draft_pack:
    - text: >-
        Alright. So you'd like access to <strong>{resource_name}</strong>?
        If you would, draft a note and I'll make sure each approver gets your request.
      buttons:
        - title: Send request
          payload: '/request_access{"reason": "-", "resource_id": "-", "resource_type": "-"}'
        - title: Nevermind
          payload: Nevermind.

  utter_laugh:
    - text: I know right?
    - text: You're hilarious.
    - text: Pretty funny.

  utter_awe:
    - text: Pretty great, right?
    - text: Yep.

  utter_send_failure_invalid:
    - text: >-
        Hmmm.... Small hiccup. Something about your request
        isn't going through our validators. Not sure what the
        problem is exactly. Try again later.

  utter_send_failure_pending:
    - text: >-
        Oh no! It looks like it took my minions too long to
        complete your request. Please try again later.

  utter_send_failure_unknown:
    - text: >-
        Houston, we've had a problem.... I'm sorry to say
        that I was unable to request access for you right now.
        But please don't lose faith in me. Simply try again later.

  utter_no_owner:
    - text: >-
        Seeing as this role has no owner, what's a bot to do? I have
        an idea! Why don't you try to become the owner? ðŸ˜œ

  utter_exclame:
    - text: Awesome!

  utter_generic:
    - text: <h1>ðŸ¤“</h1>
    - text: <h1>ðŸ™ˆ</h1>
    - text: <h1>ðŸ¤”</h1>

  utter_fanfare_sent:
    - text: <h1>ðŸ§š</h1>I've sent your request. Isn't this just magical?
    - text: <h1>ðŸ§š</h1>Sent and sent!

  utter_pending_role:
    - text: >-
        Feel free to ping me anytime. I will notify you
        once I hear from <strong>{approver_name}</strong>. Au revoir!

  utter_pending_pack:
    - text: >-
        I'll keep you posted as I hear from each approver. Keep in mind
        that even if an approver rejects a request, you'll still have access
        to any other roles of this pack that get approved. Bye for now!

  utter_bye:
    - text: Talk to you later.
    - text: Later gater.
    - text: Until next time.
    - text: Bye. I will always be here for you.

  utter_thank:
    - text: You're most welcome.
    - text: No problem.
    - text: My pleasure.
    - text: You got it.
    - text: Anytime.
    - text: Sure thing.

  utter_feeling:
    - text: I'm okay.
    - text: I'm just hanging around.
    - text: Eh. Could be better I guess.
    - text: Do you actually care?
