    post:
      security:
        - Bearer: []
      description: Add an owner to a role
      parameters:
        - name: owner
          in: body
          description: User to be added as an owner to the role
          required: true
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id of the user to be add as an owner to this role
        - $ref: '../parameters/parameters.yaml#/roleId'
      responses:
        '200':
          description: Success response with proposal id
          schema:
            $ref: '../definitions/definitions.yaml#/proposalId'
        '400':
          description: Response for a bad request
          schema:
            $ref: '../definitions/definitions.yaml#/400Error'
        '401':
          description: Response for an unauthorized request
          schema:
            $ref: '../definitions/definitions.yaml#/401Error'
        '403':
          description: Response for a forbidden request
          schema:
            $ref: '../definitions/definitions.yaml#/403Error'
        '404':
          description: Response for object not found
          schema:
            $ref: '../definitions/definitions.yaml#/404Error'
        '503':
          description: Response for an internal unknown error
          schema:
            $ref: '../definitions/definitions.yaml#/503Error'
        default:
          description: Response for an unexpected error
          schema:
            $ref: '../definitions/definitions.yaml#/error'
    delete:
      security:
        - Bearer: []
      description: Remove an owner from a role
      parameters:
        - name: member
          in: body
          description: User to be removed from the role's owner list
          required: true
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id of the user to remove as owner from this role
        - $ref: '../parameters/parameters.yaml#/roleId'
      responses:
        '200':
          description: Success response with proposal id
          schema:
            $ref: '../definitions/definitions.yaml#/proposalId'
        '400':
          description: Response for a bad request
          schema:
            $ref: '../definitions/definitions.yaml#/400Error'
        '401':
          description: Response for an unauthorized request
          schema:
            $ref: '../definitions/definitions.yaml#/401Error'
        '403':
          description: Response for a forbidden request
          schema:
            $ref: '../definitions/definitions.yaml#/403Error'
        '404':
          description: Response for object not found
          schema:
            $ref: '../definitions/definitions.yaml#/404Error'
        '503':
          description: Response for an internal unknown error
          schema:
            $ref: '../definitions/definitions.yaml#/503Error'
        default:
          description: Response for an unexpected error
          schema:
            $ref: '../definitions/definitions.yaml#/error'
